package pl.patrykv220.grupowetpcore.task;

public enum ActionType {
	RANK_POINTS_SORT_USERS(("RANK_POINTS_SORT_USERS"), 3), RANK_ONLINE_SORT_USERS(("RANK_ONLINE_SORT_USERS"),
			8), DATABASE_SAVE("DATABASE_SAVE", 15), SIDEBAR_PLAYER_RESTART("SIEBAR_PLAYER_RESTART",
					14), SIDEBAR_GLOBAL_UPDATE("SIDEBAR_GLOBAL_UPDATE", 13), RANK_OBSIDIAN_SORT_USERS(
							"RANK_OBSIDIAN_SORT_USERS",
							7), PLAYER_JOIN("PLAYER_JOIN", 17), PLAYER_QUIT("PLAYER_QUIT", 18), RANK_POINTS_SORT_GUILDS(
									"RANK_POINTS_SORT_GUILDS",
									4), RANK_BLOCKS_SORT_USERS("RANK_BLOCKS_SORT_USERS", 6), RANK_SORT_GUILDS(
											"RANK_SORT_GUILDS", 2), SIDEBAR_PLAYER_UPDATE("SIDEBAR_PLAYER_UPDATE",
													12), RANK_SORT_USERS("RANK_SORT_USERS", 1), RANK_REFIL_SORT_USERS(
															"RANK_REFIL_SORT_USERS", 9), DATABASE_LOAD("DATABASE_LOAD",
																	16), RANK_KILLS_SORT_USERS("RANK_KILLS_SORT_USERS",
																			10), SIDEBAR_PLAYER_SET(
																					"SIDEBAR_PLAYER_SET",
																					11), RANK_KOX_SORT_USERS(
																							"RANK_KOX_SORT_USERS", 5);

	private ActionType(final String s, final int n) {
	}
}
